apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web # configured in deployment
  ports:
    - port: 3000 #port accessed by others in the cluster
      targetPort: 3000 #port inside the container